version: 2
models:
  - name: stg_orders
    description: Cleaned orders with consistent types and timestamps.
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_status
        tests:
          - accepted_values:
              values: ['approved', 'created', 'delivered', 'shipped', 'canceled', 'invoiced', 'processing', 'unavailable']
  - name: stg_order_items
    columns:
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: order_item_id
        tests: [not_null]
  - name: stg_order_payments
    columns:
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
  - name: stg_order_reviews
    columns:
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]
  - name: stg_sellers
    columns:
      - name: seller_id
        tests: [unique, not_null]
  - name: stg_products
    columns:
      - name: product_id
        tests: [unique, not_null]
