# top level entities belong to default profile (dev) which is intended to be used in local development

sources:
  events:
    type: dlt_portable_data_lake_demo.sources.github.github_event
    archive: ${project_dir}/_data/2024-10-13-15.json.gz
    with_args:
      max_table_nesting: 2

destinations:
  # data lake where raw event data goes
  delta_lake:
    type: filesystem
    bucket_url: ${tmp_dir}delta_lake
  # warehouse where data aggregated by transformations and shared by data scientist user goes
  warehouse:
    type: duckdb
    credentials: ${tmp_dir}warehouse.db

datasets:
  # dataset with raw data
  github_events_dataset:
    "on":
      - delta_lake
  reports_dataset:
    "on":
      - warehouse

pipelines:
  events_to_lake:
    source: events
    destination: delta_lake
    dataset_name: github_events_dataset
    progress: enlighten
    # refresh: "drop_sources"


cache:
  engine: duckdb

transformations:
  aggregate_issues:
    engine: dbt
    inputs:
      - dataset_name: github_events_dataset
        tables:
          "issues_event": "issues_event"
    outputs:
      - dataset_name: reports_dataset
        tables:
          dim_issues_actors: dim_issues_actors
          dim_issues_repos: dim_issues_repos


profiles:
  # production profile using s3 and snowflake
  prod: &prod_profile
    destinations:
      warehouse:
        type: snowflake
        credentials:
  # <<: !include prod.profile.yml
  # data access and sharing profile for data user
  access:
    # uses production profile (but with different credentials)
    <<: *prod_profile
    # restrict access to datasets
    datasets: &dataset_contracts
      github_events_dataset:
        # no new tables, no column changes
        contract: freeze
      reports_dataset:
        # allow new tables but no column changes
        contract:
          tables: evolve
          columns: freeze
          data_type: freeze

    runtime:
      log_level: ERROR

  # TODO: move test profiles to a separate file that is included from test folder
  tests: &tests_profile
    {}
    # project:
    #   # create temp dir for tests level up
    #   tmp_dir: ${project_dir}../tests/_storage/

  tests-access:
    <<: *tests_profile
    datasets:
      <<: *dataset_contracts
      scratchpad_dataset:
        "on":
          - delta_lake

# default log level
runtime:
  log_level: WARNING

# generate load_id for native arrow tables
normalize:
  parquet_normalizer:
    add_dlt_load_id: true
