[project]
name = "06-analyze-data-in-iceberg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.4",
    "scikit-learn>=1.6.1",
    "tower>=0.3.6",
]
