[project]
name = "05-iceberg-write"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyarrow>=19.0.1",
    "requests>=2.32.3",
    "tower>=0.3.6",
]
