[project]
name = "08-dlt-plus-iceberg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt-plus>=0.7.0",
    "dlt[duckdb]>=1.7.0",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
]
